### PR TITLE
Allow links to containers outside of the project

### LINKED ISSUE #159: Link to an existing container
Maybe it could work like this:

```yaml
links:
  - :existing_container_name
```

### PR DESCRIPTION
**Pull request by jbalonso**
Resolves #159. I believe this PR needs tests (existing ones should be ok), but I wanted to start a conversation around it.

### CODE REVIEW

**Comment by aanand** [comment]
LGTM

**Comment by tsileo** [comment]
Any update on this ?

**Comment by dnephin** [comment]
LGTM

**Comment by thaJeztah** [comment]
Oh yeah!

**Pull request merged**
