### PR TITLE
Add Docker docs.docker.com meta-data, and reflow to 80-chars to simplify GH diffs

### PR DESCRIPTION
**Pull request by SvenDowideit**
to go along with https://github.com/docker/docker/pull/10173 for the 1.5 docs.

I have only pulled in these 4 files for now.

### CODE REVIEW

**Comment by aanand** [comment]
LGTM

**Comment by dnephin** [comment]
LGTM

**Comment by fredlf** [comment]
LGTM

**Comment by SvenDowideit** [comment]
@fredlf can you please check my rebase for holes?

**Comment by fredlf** [comment]
LGTM more

**Pull request merged**
