### PR TITLE
Tweaks to the rails tutorial to bring it inline with rails 4.2 release

### PR DESCRIPTION
**Pull request by madwire**
Due to a change in Rack, rails server now listens on localhost instead of 0.0.0.0 by default.

Please also see #750

### CODE REVIEW

**Comment by aanand** [comment]
Nice. Would you mind putting in an explicit tag for the `ruby` image too? Or I can see that giving us headaches down the line.

**Comment by madwire** [comment]
@aanand I think its better to be explicit, people will simply replace the version(s) for a more recent one like they are doing anyway.

**Comment by aanand** [comment]
Thanks. LGTM

**Comment by aanand** [comment]
ping @bfirsh @dnephin

**Comment by dnephin** [comment]
LGTM (for what I know of rails, which is not much)

**Pull request merged**
