### PR TITLE
Link correction

### PR DESCRIPTION
**Pull request by stevepereira**

### CODE REVIEW

**Comment by aanand** [comment]
`.html` is correct - the docs will eventually be hosted on docs.docker.com as rendered HTML.

**Comment by stevepereira** [comment]
....
Why not merge and then update it when 'eventually' becomes 'actually'? Leaving it broken until 'eventually' seems like something of a usability issue.

**Comment by aanand** [comment]
Because the docs aren't meant to be consumed at github.com/docker/fig. Their current location is www.fig.sh, where they work just fine.

**Comment by stevepereira** [comment]
Aha!

:) well done then!

**Pull request closed without merging**
