### PR TITLE
Revises Compose cli reference

### PR DESCRIPTION
**Pull request by fredlf**
signed off by Fred Lifton (fred@docker.com)

### CODE REVIEW

**Comment by bfirsh** [comment]
Nice, thank you! This is so much better.

Commit needs signing off, though... Perhaps your comment in the PR counts? IANAL.

**Comment by fredlf** [comment]
IANL either, but I've been told the sign-off is kind of irrelevant for docs. I don't know why my sign-off doesn't work in this repo, I poked around for awhile, couldn't solve it, moved on to more important things, figuring comment was good enough.

**Comment by bfirsh** [comment]
No, don't worry about it. It don't think it matters if you've agreed to the DCO in the pull request, just nice to have a green tick on the build. ;)

If you're using the Git command-line client, you can pass the `--signoff` option to the commit command to add it.

**Comment by Starefossen** [comment]
You can use `--amend` to add to the previous commit like this:

```
git commit --amend --signoff
```

**Comment by fredlf** [comment]
Thanks, @Starefossen . That's not working for some reason. I'll get it figured at some point.

**Comment by bfirsh** [comment]
LGTM

**Comment by aanand** [comment]
The `FIG_*` environment variables are deprecated in favour of `COMPOSE_PROJECT_NAME` and `COMPOSE_FILE`.

**Comment by aanand** [comment]
Eh, I'll fix that separately. LGTM

**Pull request merged**
