### PR TITLE
Bash completion for fig command

### PR DESCRIPTION
**Pull request by albers**
This work is based on the wonderful bash completion for the docker command.
I placed it in the same location as in the docker repository.

### CODE REVIEW

**Comment by aanand** [comment]
Great stuff. It took me a while to get this working, which I think points to a few documentation refinements:

- On my Mac, bash completion isn't installed by default; assuming that's universal, we should add a note about installing it. `brew install bash-completion` worked for me.

- I had to put the script in `/usr/local/etc/bash_completion.d`, because of where Homebrew installs stuff, so it should be clear to other brew users that they need to put it there.

I also had two other thoughts:

- I think we should put the completion installation instructions on the completion page, and just link to it from the Fig installation page.

- I like the tutorial style, but I think it's safe to assume anyone interested in bash completion will know what it is, so let's structure the page as:
  - Installation instructions
  - List of what types of completions are supported, with short examples of each.

**Comment by albers** [comment]
@aanand Documentation is adjusted to your suggestions.
After this is merged, completion should be added to #806.

If there is some documentation on how to perform a release, it should be extended so that completion is included in a release and the download link be adjusted.

**Comment by albers** [comment]
Added support for new option `fig up --no-build`

**Comment by albers** [comment]
@aanand @dnephin I'd like to mention that I'd happily take over the rebranding task for the completion, either in this PR or in a separate one after a merge, so this aspect should not block inclusion in the next milestone or release. Is there anything missing in this PR?

**Comment by dnephin** [comment]
LGTM

**Comment by aanand** [comment]
It's looking good. Once the `rebrand` branch has calmed down, I'll ping you so you can rebase onto it in preparation for release.

**Comment by bfirsh** [comment]
If this is good, why don't we merge it now before the rename?

**Comment by thaJeztah** [comment]
> If this is good, why don't we merge it now before the rename?

My thoughts.

Also, iirc a `fig` stub would be included after the rebranding (so I would still be able to do `fig up` and it would call `machine up` in the background)? In that case, completion for `fig` would still be relevant.

**Comment by aanand** [comment]
OK, going to merge and add a TODO to #835.

**Comment by aanand** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks @aanand! (Lol noticed my s/machine/compose/ typo)

**Comment by albers** [comment]
Thanks!

> Also, iirc a fig stub would be included after the rebranding (so I would still be able to do fig up and it would call compose up in the background)? In that case, completion for fig would still be relevant.

The [last line of the completion script](https://github.com/docker/fig/blob/master/contrib/completion/bash/fig#L316) registers the completion function `_fig` for the `fig` executable. It could as well be registered for both `fig` and `compose`.

**Comment by albers** [comment]
This closes #338.

**Comment by thaJeztah** [comment]
> It could as well be registered for both fig and compose.

Ooh, that's nice! Not too familiar with completion scripts, but that's handy :)

Thanks for your contribution!

**Comment by lePoxy** [comment]
I'm working on a zsh equivalent.

**Comment by thedrow** [comment]
Care to issue a pull request to [bash-it](https://github.com/revans/bash-it/) with the same file?

**Pull request merged**
